# Generated by Django 3.2.12 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name', max_length=100)),
                ('email', models.EmailField(help_text='Customer email')),
                ('address', models.TextField(help_text='Delivery address')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total order price', max_digits=10)),
                ('items', models.JSONField(help_text='Order items as JSON (product IDs and quantities)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
