# Generated by Django 3.2.12 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(help_text='Product description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', max_length=500, null=True)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
